// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3YkyCC96SL6xGnOYllw172mWtRaxlO8',
    appId: '1:598944284551:android:a1d55d36f4122b8719dd22',
    messagingSenderId: '598944284551',
    projectId: 'shoppingapp-2f2ab',
    storageBucket: 'shoppingapp-2f2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEesX4FiGmJ_saXsJWy7KNTAXx5pn1gpc',
    appId: '1:598944284551:ios:0a5bff07cad0abe619dd22',
    messagingSenderId: '598944284551',
    projectId: 'shoppingapp-2f2ab',
    storageBucket: 'shoppingapp-2f2ab.firebasestorage.app',
    androidClientId: '598944284551-bgne24jooc7t6r5aqn794bvcoah2tdg5.apps.googleusercontent.com',
    iosClientId: '598944284551-u5qif9374enqvj5570ahfj27gvbamquu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}